### ISSUE TITLE
(node:388) UnhandledPromiseRejectionWarning: ReferenceError: sentMessage is not defined

### ISSUE THREAD

**Issue by YourDeadPixels** [pixl-studios/Project---L.I.S.A.#2]
at Object.run (/home/runner/commands/miscellaneous/suggest.js:54:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:388) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:388) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by YourDeadPixels** [comment]
sentMessage not defined within suggest.js Meaning var sentMessage = <what it needs to equal>
