### ISSUE TITLE
Missing token

### ISSUE THREAD

**Issue by YourDeadPixels** [pixl-studios/Project---L.I.S.A.#5]
SyntaxError: /home/REDACTED-FOR-PRIVACY/config.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:708:27)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/REDACTED-FOR-PRIVACY/index.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)

**Comment by YourDeadPixels** [comment]
Unable to fix as of 7/3/19 9:27 PM as the Google Cloud Console Editor will not save any files that have been edited and clears them.

**Comment by YourDeadPixels** [comment]
Fixed by not using google cloud platform :P
