### ISSUE TITLE
>help Empty Fields error (doesn't endanger nodejs process)

### ISSUE THREAD

**Issue by YourDeadPixels** [pixl-studios/Project---L.I.S.A.#6]
```
RangeError: RichEmbed field values may not be empty.
    at RichEmbed.addField (/home/runner/node_modules/discord.js/src/structures/RichEmbed.js:166:34)
    at categories.forEach.category (/home/runner/commands/miscellaneous/help.js:33:27)
    at Array.forEach (<anonymous>)
    at Object.run (/home/runner/commands/miscellaneous/help.js:29:24)
    at module.exports (/home/runner/events/guild/message.js:28:33)
    at Client.emit (events.js:189:13)
    at MessageCreateHandler.handle (/home/runner/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/runner/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (/home/runner/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/home/runner/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
RangeError: RichEmbed field values may not be empty.
    at RichEmbed.addField (/home/runner/node_modules/discord.js/src/structures/RichEmbed.js:166:34)
    at categories.forEach.category (/home/runner/commands/miscellaneous/help.js:33:27)
    at Array.forEach (<anonymous>)
    at Object.run (/home/runner/commands/miscellaneous/help.js:29:24)
    at module.exports (/home/runner/events/guild/message.js:28:33)
    at Client.emit (events.js:189:13)
    at MessageCreateHandler.handle (/home/runner/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/runner/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (/home/runner/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/home/runner/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
```

**Comment by chroventer** [comment]
@YourDeadPixels, it is a RangeError as mentioned in the error itself, this is thrown when the `embed.addField()` is empty.
Check out this line:
```js
embed.addField(`❯ ${capitalise} [${dir.size} commands]:`, dir.map(c => `\`${c.config.name}\`,`).join(" ") /** it seems to me that this line is causing the error */)
```
Try to log the following code in the console by `console.log()`
```js
dir.map(c => `\`${c.config.name}\`,`).join(" ");
```
