### ISSUE TITLE
Discord Undefined

### ISSUE THREAD

**Issue by YourDeadPixels** [pixl-studios/Project---L.I.S.A.#7]
(node:408) UnhandledPromiseRejectionWarning: ReferenceError: Discord is not defined
    at Object.run (/home/runner/commands/miscellaneous/partners.js:13:15)
    at module.exports (/home/runner/events/guild/message.js:28:33)
    at Client.emit (events.js:189:13)
    at MessageCreateHandler.handle (/home/runner/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/runner/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (/home/runner/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/home/runner/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/home/runner/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:189:13)
    at Receiver.receiverOnMessage (/home/runner/node_modules/ws/lib/websocket.js:789:20)
(node:408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:408) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by YourDeadPixels** [comment]
Easy Fix, 
`const Discord = ('discord.js')`
